name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧼 Run linter
        run: npm run lint

      - name: 🧪 Run unit + snapshot tests
        run: npm run test -- --run

      - name: 🧪 Run E2E tests (Playwright)
        run: |
          npx playwright install --with-deps
          npm run dev &
          npx wait-on http://localhost:5173
          npm run e2e
